from .dino_multiscale_classifier import DinoMultiScaleClassifier as BaselineDinoMultiScaleClassifier
from .dino_multiscale_gated_classifier import DinoMultiScaleClassifier as GatedDinoMultiScaleClassifier
from .dino_multiscale_cross_gated_classifier import DinoMultiScaleClassifier as CrossGatedDinoMultiScaleClassifier
from .dino_multiscale_parallel_classifier import DinoMultiScaleClassifier as ParallelDinoMultiScaleClassifier
from .dino_multiscale_coag_classifier import DinoMultiScaleClassifier as CoAGDinoMultiScaleClassifier
